version: 2
registries:
  gradle-plugin-portal:
    type: maven-repository
    url: https://plugins.gradle.org/m2
    username: dummy # Required by dependabot
    password: dummy # Required by dependabot
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    registries:
      - gradle-plugin-portal
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/example/configure_custom_generator_strategy"
    registries:
      - gradle-plugin-portal
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/example/configure_different_jooq_sources_for_same_target_source_set"
    registries:
      - gradle-plugin-portal
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/example/configure_generation_tool_execution"
    registries:
      - gradle-plugin-portal
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/example/configure_incremental_build_and_build_caching_participation"
    registries:
      - gradle-plugin-portal
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/example/configure_jooq_config_normalization"
    registries:
      - gradle-plugin-portal
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/example/configure_jooq_version_from_spring_boot"
    registries:
      - gradle-plugin-portal
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/example/configure_jooq_with_flyway"
    registries:
      - gradle-plugin-portal
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/example/configure_jvm_args"
    registries:
      - gradle-plugin-portal
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/example/configure_task_dependencies"
    registries:
      - gradle-plugin-portal
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/example/configure_toolchain_gradle_dsl"
    registries:
      - gradle-plugin-portal
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/example/configure_toolchain_kotlin_dsl"
    registries:
      - gradle-plugin-portal
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/example/extract_precompiled_script_plugin"
    registries:
      - gradle-plugin-portal
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/example/extract_script_file"
    registries:
      - gradle-plugin-portal
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/example/specify_jooq_config_xml_schema_version"
    registries:
      - gradle-plugin-portal
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/example/use_groovy_dsl"
    registries:
      - gradle-plugin-portal
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/example/use_kotlin_dsl"
    registries:
      - gradle-plugin-portal
    schedule:
      interval: "daily"
